// PRODUCT
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS';
export const PRODUCT_FAILED = 'PRODUCT_FAILED';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const UPDATE_PRODUCT_SAGA = 'UPDATE_PRODUCT_SAGA';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_PRODUCT_SAGA = 'DELETE_PRODUCT_SAGA';
